name: whatsapp-proyect
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26
  - pandas
  - matplotlib
  - seaborn
  - streamlit
  - pyyaml
  - wordcloud
  - pip
  - pip:
      - hydralit_components
