[logger]
level = "warning"

[client]
toolbarMode = "minimal"

[theme]
primaryColor="#7AE2CF"
backgroundColor="#06202B"
secondaryBackgroundColor="#077A7D"
textColor="#F5EEDD"
linkColor = "#7AE2CF"
font="monospace"
baseRadius = "large"